apiVersion: v1
kind: Service
metadata:
  name: cat-backend-service
spec:
  type: NodePort
  selector:
    app: cat-backend
  ports:
    - port: 8123
      targetPort: 8123
      nodePort: 30081
      protocol: TCP     
      name: http